### ISSUE TITLE
Microphone isn't included in 0.5.0 on NPM

### ISSUE THREAD

**Issue by albatrocity** [tessel/tessel-av#10]
Just a heads up, `lib/microphone.js` isn't in the directory delivered by an `npm install` at version `0.5.0`. May need a publish?

**Comment by rwaldron** [comment]
I don't understand... this isn't a bug is it? `Microphone` support isn't released yet.

**Comment by rwaldron** [comment]
Released tessel-av@0.6.0

**Comment by albatrocity** [comment]
@rwaldron ah, no worries, I was just poking around in the master branch and didn't know how the releases were managed. Sorry for the noise!

**Comment by rwaldron** [comment]
No, no... it was a good reminder to me to get it out. Now people can play with it over the weekend. Unfortunately, I haven't written any docs yet.
