### ISSUE TITLE
Support for camera-vc0706

### ISSUE THREAD

**Issue by OR13** [tessel/tessel-av#17]
I realize I failed to read the bold lettering, telling me that this hardware is useless on my T2. However, I have paid $50, and so have a few other people from the forums. Lets discuss what it would take to make this hardware module work, so we don't feel sad.

**Comment by rwaldron** [comment]
I'm sorry, but that hardware is **incompatible** with the Tessel 2.

**Comment by rwaldron** [comment]
https://github.com/tessel/project/issues/222
