### ISSUE TITLE
other ways to make noise

### ISSUE THREAD

**Issue by boneskull** [tessel/tessel-av#20]
Is there a way to produce sound via a passive buzzer or speaker wired to a pin? Could I simply use plain ol PCM and some Node module to do this, then output directly to a pin?

8-bit audio quality is good enough for my use case. I want to produce audible feedback (clicks/beeps) when a user interacts with my device. 

Is a USB audio adapter my only option? seems like overkill.

**Comment by HipsterBrown** [comment]
`tessel-av` is focused on USB-enabled media devices, like speakers, microphones, and webcams, so I don't believe this package should support passive buzzers or breakout speakers. 

It is possible to use a [piezo buzzer](http://tinkersphere.com/buzzers/1339-piezo-buzzer-5vac-breadboard-compatible.html) with the [`tessel` PWM API](https://tessel.gitbooks.io/t2-docs/content/API/Hardware_API.html#pwm-pins). I've started building a library to make this easier but until that's done, you can check out the [Johnny-Five Piezo notes frequencies](http://johnny-five.io/api/piezo/) for the `tessel.pwmFrequency` and use a `pin.pwmDutyCycle` of about 0.2 to get the same effect.
