### ISSUE TITLE
Fix dest.end bug

### ISSUE THREAD

**Issue by rwaldron** [tessel/tessel-av#21]
Originally reported here https://forums.tessel.io/t/dest-end-is-not-a-function-error/2874 this was fixed in v0.15.1, but I forgot to create an issue for it.

**Comment by EnshaednHiker** [comment]
Hey, I'm still getting this error:

![image](https://cloud.githubusercontent.com/assets/23422635/26524077/86cbdd2a-42ed-11e7-846b-5c88a186abf9.png)

I'm only using this code: 

```const av = require('tessel-av');

const camera = new av.Camera();
const capture = camera.capture();

capture.on('data', function(data) {
  console.log("foo camera")
});
```
I'm on Windows 10 with the Creators update and my tessel environment is:

```λ t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-02A3B6C734F6.
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.4
INFO t2-firmware: 0.0.16
INFO Node.js: 4.5.0```

**Comment by rwaldron** [comment]
Thanks for the report. Can you...

- Confirm the version of tessel-av that you have installed
- Share a link to the exact camera that you're using

**Comment by EnshaednHiker** [comment]
"tessel-av": "^0.18.0"

https://www.amazon.com/gp/product/B0092QJRPC/ref=oh_aui_search_detailpage?ie=UTF8&psc=1

**Comment by rwaldron** [comment]
Ok, thanks! I'm traveling presently, but will be home this weekend and will be able to address this hopefully on Monday—sorry for the delay :(

**Comment by EnshaednHiker** [comment]
No worries! I appreciate your diligence.

**Comment by opkiler22789** [comment]
I join too I receive such error.
Using the  [code](https://github.com/tessel/tessel-av/blob/master/eg/camera-demo.jsl)

**Comment by knaut** [comment]
Also experiencing this error. Downgraded to v0.15.1, no change. Mac OS 10.12.2

**Comment by rwaldron** [comment]
Please try tessel-av@0.19.0

Thanks!

**Comment by EnshaednHiker** [comment]
I definitely will! Thank you!

**Comment by knaut** [comment]
The 0.19.0 seemed to fix the issue for me, both with demo code and my own code. A couple times the captured image response seems to hang forever, but I'm wondering if that's a network issue on my side. Rebooting the Tessel seems to make it problem go away.

Other than that, works like a charm. Thanks @rwaldron!

**Comment by rwaldron** [comment]
That's great news :)
