### ISSUE TITLE
how to use microphone? 

### ISSUE THREAD

**Issue by aquaminer** [tessel/tessel-av#23]
hello how to use a microphone ?
For example, how to write to a file?

**Comment by aquaminer** [comment]
@rwaldron please reply

**Comment by ludovicriffault** [comment]
Hi,

I'm also interested to know how to get data from USB microphone. Any help would be very appreciated!

Thanks! @rwaldron

**Comment by rwaldron** [comment]
There is an example program in `eg/`: https://github.com/tessel/tessel-av/blob/master/eg/microphone.js
