### ISSUE TITLE
Can't seem to play mp3s

### ISSUE THREAD

**Issue by johnnyman727** [tessel/tessel-av#5]
I ran `opkg update` and `opkg install madplay`, downloaded a song with the appropriate filename (and added it to `.tesselinclude` and deployed the script. The script just completes without any errors pretty much immediately and I hear no sound. I've tried both the green and pink audio jack holes. Any idea what the issue might be?

**Comment by rwaldron** [comment]
>  Any idea what the issue might be?

Nope, no idea :\

**Comment by rwaldron** [comment]
@johnnyman727 still having issues? I've never been able to reproduce the problem

**Comment by johnnyman727** [comment]
Not sure - I don't have an audio with me. Will be back in the states next week and will try again.

**Comment by johnnyman727** [comment]
I had a chance to try this out again today. Besides [this issue I encountered with the CLI](https://github.com/tessel/t2-cli/issues/691), the program played audio as expected:
```
var path = require('path');
var av = require('tessel-av');
var mp3 = path.join(__dirname, 'vivaldi.mp3');
var sound = new av.Player(mp3);

sound.play();
```

On a related note: is it possible to add the capability to change the volume?

**Comment by rwaldron** [comment]
Should be able to do: 

```js
var sound = new av.Player(mp3);

sound.play({
  a: ...
});
```

This allows for any of these: https://github.com/tessel/tessel-av/blob/master/madplay.md
