### ISSUE TITLE
No 'data' event on camera in stream mode

### ISSUE THREAD

**Issue by josser** [tessel/tessel-av#8]
Hi! 
I'm trying to run examples from readme.md but something is wrong and I can't figure out where exactly. 

So, i'm running this code (taken from examples + added console.log's): 

```javascript
var express = require('express');
var app = express();
var server = require('http').Server(app);
var io = require('socket.io')(server);
var os = require('os');
var path = require('path');
var cp = require('child_process');
var port = 8080;

var av = require('tessel-av');

server.listen(port, function () {
  console.log(`http://${os.hostname()}.local:${port}`);
});

app.use(express.static(path.join(__dirname, '/public')));

io.on('connection', (socket) => {
  var camera = new av.Camera();
  console.log('created camera');
  socket.on('ready', () => { 
    camera.stream(); 
    console.log('socket ready');
  });
  camera.on('data', (data) => {
    console.log('on camera data')
    socket.emit('image', data.toString('base64'));
  });
});

process.on("SIGINT", _ => server.close());
```

And I see all console.logs except 'on camera data', so I think sockets is working fine (also no errors in browser console) but camera is not emitting 'data' event. 
Webcamera is working because another example with .capture -> send via simple http is working fine. 

Another small question: why default settings for capture is limited to 320x240, I have logitech c240 which is 720p webcam. So it would be great to have ability to capture bigger images. 

Thank you and sorry for my bad english )

**Comment by rwaldron** [comment]
Not sure what you're experiencing here, and I can't reproduce it :( I copied your exact code here and ran it with the examples: 


```
$ t2 run 8.js
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Building project.
INFO Writing project to RAM on bishop (1199.104 kB)...
INFO Deployed.
INFO Running 8.js...
http://bishop.local:8080
created camera
socket ready
on camera data
on camera data
on camera data
on camera data
on camera data
on camera data
on camera data
on camera data
on camera data
on camera data
on camera data
on camera data
```

Here's me in the browser: 

![](https://i.gyazo.com/088783c51f98ded60e93d0447d66d90b.png)

The only thing I noticed was a few seconds of delay between "socket ready" and the first "on camera data".


> Another small question: why default settings for capture is limited to 320x240, I have logitech c240 which is 720p webcam. So it would be great to have ability to capture bigger images.

Have a look at my explanation here: https://github.com/tessel/tessel-av/issues/9#issuecomment-207867151

**Comment by josser** [comment]
Cool! Thank you for explanation, could it be possible that I have this issue because I have tried on 0.0.11 firmware?
I didn't tried after 0.0.12 update, but I'll try today and i'll report results.

**Comment by rwaldron** [comment]
I don't think so, but I can't say for sure, so I look forward to your test results.

**Comment by josser** [comment]
ok, tried on 0.0.12 with another camera, still no event,  :( 
Can you suggest good place to add some debug info?

**Comment by albatrocity** [comment]
@josser I was running into the exact same thing with the same camera. Trying sourcing `tessel-av` from github. The NPM package seems to be out of date. 

```
"dependencies": {
    "tessel-av": "tessel/tessel-av"
  }
```

I was able to get video stream data from the Logitech c240 after doing this. Hope this works!

**Comment by rwaldron** [comment]
Please try tessel-av@0.6.0

**Comment by albatrocity** [comment]
`0.6.0` works for me with `stream` and a Logitech c240

**Comment by rwaldron** [comment]
@albatrocity great! Sorry for the delay releasing that :\

**Comment by rwaldron** [comment]
@josser can you confirm as well? I can't close until you ☑️

**Comment by josser** [comment]
@rwaldron Oh, sure, will check in a few hours. Sorry for so slow responses!

**Comment by josser** [comment]
@rwaldron Working! Thank you for your work and patience!

**Comment by Arrow7000** [comment]
Hi, I am having the exact same problem. I'm using tessel-av v0.8.0. 

Here's the code, virtually identical to @josser's, except I have different console.logs. 

```
var express = require('express');
var app = express();
var server = require('http').Server(app);
var io = require('socket.io')(server);
var os = require('os');
var path = require('path');
var cp = require('child_process');
var port = 8080;

var av = require('tessel-av');

server.listen(port, function() {
    console.log(`http://${os.hostname()}.local:${port}`);
});

app.use(express.static(path.join(__dirname, '/public')));

io.on('connection', (socket) => {
    console.log('Connection received');
    var camera = new av.Camera();

    socket.on('ready', () => {
        console.log('Socket\'s ready');
        camera.stream();
    });
    camera.on('data', (data) => {
        console.log('Data coming out of camera');
        socket.emit('image', data.toString('base64'));
    });
});

process.on("SIGINT", _ => server.close());
```

This is what happens when I run it and connect from a browser:

```
INFO Looking for your Tessel...                                                                                                           
INFO Connected to aa-tessel.                                                                                                              
INFO Building project.                                                                                                                    
INFO Writing project to RAM on aa-tessel (1274.368 kB)...                                                                                 
INFO Deployed.                                                                                                                            
INFO Running video.js...                                                                                                                  
http://aa-tessel.local:8080                                                                                                               
Connection received                                                                                                                       
Connection received                                                                                                                       
Socket's ready 
```

And that's all that ever happens. `'Data coming out of camera'` never gets logged to the console. Any help would be appreciated!

**Comment by johnnyman727** [comment]
@rwaldron might have some tips for how to debug.

**Comment by Arrow7000** [comment]
Thanks :smile: I just tweeted at him hoping he'll take a look at this.

**Comment by rwaldron** [comment]
I can take a look, but until tomorrow

**Comment by rwaldron** [comment]
In the mean time, can you link to the camera you're using? Thanks!

**Comment by Arrow7000** [comment]
It's this one: http://www.elpcctv.com/mi5100-5mp-usb-camera-module-usb20-aptina-125inch-color-cmos-sensor-100degree-lens-p-221.html. 

The model ID on the front says `usb500w05g`.

Here's a pic of mine:

![rsz_1whatsapp_image_2016-08-20_at_220750](https://cloud.githubusercontent.com/assets/13225609/17833994/ea8f2672-6725-11e6-90e3-366c442a0c1b.jpg)

**Comment by rwaldron** [comment]
Am I reading that correctly, the minimum frame dimensions are 640x480?

**Comment by Arrow7000** [comment]
It looks like it yes

**Comment by Arrow7000** [comment]
Let me know if there's anything else you need to know!

**Comment by rwaldron** [comment]
@Arrow7000 I'm not sure there is much to do, the max dimensions have always been 320x240 (this is a system memory constraint). There are a few things I would like to try, and I'd also like to get one of these cameras for myself and see if there is anything that can be done to accommodate higher frame dimensions. 

Have you tried taking a still image? https://github.com/tessel/tessel-av#avcamera-examples

If that also doesn't work, I will write up a more specific "smoke test"

**Comment by rwaldron** [comment]
Can you confirm that this is the same camera: https://www.amazon.com/ELP-5megapixel-undistorted-correctable-Camera-2592x1944/dp/B012CH5F58

**Comment by Arrow7000** [comment]
@rwaldron yes that is the same camera. 

So I can in fact take pictures with it, I tried it with this script: 

```
var av = require('tessel-av');
var os = require('os');
var http = require('http');
var port = 8080;
var camera = new av.Camera();

http.createServer((request, response) => {
  response.writeHead(200, { 'Content-Type': 'image/jpg' });

  camera.capture().pipe(response);

}).listen(port, () => console.log(`http://${os.hostname()}.local:${port}`));
```

and that does result in a picture whenever I visit the browser, like this one: 

![tesselimg](https://cloud.githubusercontent.com/assets/13225609/17838611/5b1d7f8a-67c9-11e6-9845-7ca508f0b026.jpg)

**Comment by rwaldron** [comment]
Ok, that's good (even if it's bad). I will purchase that camera have it shipped asap. I appreciate your patience as we work through this

**Comment by Arrow7000** [comment]
Thanks @rwaldron, I appreciate you working on this! :)

**Comment by rwaldron** [comment]
@Arrow7000 my camera _should_ be delivered tomorrow, will keep you posted

**Comment by Arrow7000** [comment]
Excellent, thanks for the update!

**Comment by rwaldron** [comment]
@Arrow7000 so I received my camera earlier this week and have had a few runs at this issue. Here are the things I've learned:

- Using ffmpeg (which backs tessel-av)
  - 640x480 is the smallest dimensions this camera produces, which is problematic for ffmpeg streams on a Tessel 2—that's just too big (which is why I hard-capped the dimensions at 320x240)
    - If you try to explicitly set smaller dimensions on the _input_, it will refuse and you'll get 640x480 
    - 640x480 is set to 30fps 
    - If you try to explicitly set lower fps on the _input_, it will refuse and you will get 30fps
    - So far, each frame is twice as big and expected to be processed twice as frequently, which brings me to the A-bomb: 
      - The output of `top` while running ffmpeg:
      ```
        PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
       1887  1823 root     R    42576  69%  99% ffmpeg -y -v fatal -f v4l2 -i /dev/vi
      ```
      ... So it's not that you're not getting "data" events, it's the there is not enough resources to do anything else.

- Using mjpg_streamer (which is awesome if all you want is a stream and no processing involved)
  - Life is good. 
    ```
    mjpg_streamer -i "./input_uvc.so -n -q 50 -r QVGA -d /dev/video0" -o "./output
    _http.so -p 8080"
    MJPG Streamer Version: svn rev: exported
     i: Using V4L2 device.: /dev/video0
     i: Desired Resolution: 320 x 240
     i: Frames Per Second.: not limited
     i: Format............: JPEG
     i: TV-Norm...........: DEFAULT
    i: The format asked unavailable, so the width 640 height 480
     o: www-folder-path...: disabled
     o: HTTP TCP port.....: 8080
     o: username:password.: disabled
     o: commands..........: enabled
    ```
    - Note: "    i: The format asked unavailable, so the width 640 height 480" that's because mjpg_streamer defaults to 320x240, but this camera will refuse that size. 
    - If i tried to add `-f 15` (limit fps to 15), the init output would include: " i: FPS coerced ......: from 15 to 30"
    - Opening that stream in a browser is pretty amazing. In my case, I just ran the command shown above and then opened `http://ash.local:8080/?action=stream` (ash is the name of my tessel) and it was very smooth. 
    - So what about the resource consumption? This is where mjpg_streamer utterly destroys ffmpeg: 
    ```
    PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
    1926  1823 root     S    11860  19%   7% mjpg_streamer -i ./input_uvc.so -n -q    
    ```
    ... Yeah, NO JOKE.
    - For what it's worth, we're using mjpg_streamer in an upcoming sparkfun tutorial, which I will share with you here so you can see how we're including it in our Node.js application: https://github.com/bocoup/j5ik-reconbot-tessel-edition
      - First you'd `t2 run install.js` to install the package
      - Then just `t2 run index.js` as normal. The `.tesselinclude` and `video.sh` are _required_

**Comment by johnnyman727** [comment]
Fantastic analysis @rwaldron!

**Comment by rwaldron** [comment]
There's more! We decided to push mjpg_streamer as far as we could, the criteria being: 

1. Must play smoothly in the browser
2. Must not crash on process end (this can happen)

With that in mind, we started at the top (why the hell not?!) 


Idle Memory usage: 

```
Mem: 23252K used, 38236K free, 2528K shrd, 1480K buff, 5516K cached
```

Base command & options: 

```
mjpg_streamer -i "./input_uvc.so -n -q 50 -r WxH -d /dev/video0" -o "./output_http.so -p 8080"
```


| Dimensions @ fps  | VSZ | CPU | Played At All? | Played Smoothly? | Crashed On Process End? | 
| ----------------- | --- | --- | -------------- | ---------------- | ----------------------- |
| 2592x1944 @ 15fps |     |     | No             |                  |                         |
| 2048x1536 @ 15fps | ~86% | ~22% | Yes          | For medium bursts, then lag | Yes. Seg Fault | 
| 1600x1200 @ 15fps | ~59% | ~11% | Yes          | For medium bursts, then lag | Yes. Seg Fault | 
| 1280x1024 @ 15fps | ~45% | ~14% | Yes          | For medium bursts, then lag | No | 
| 1920x1080 @ 30fps | ~62% | ~23% | Yes          | Yes | No |
| 1280x720  @ 30fps | ~33% | ~17% | Yes          | Yes (See video) | No |
| 800x600   @ 30fps | ~27% | ~16% | Yes          | Yes | No |
| 640x480   @ 30fps | ~23% | ~13% | Yes          | Yes | No |


https://www.youtube.com/watch?v=pleHac8UWXs


I'm going to work on replacing ffmpeg with mjpg_streamer in tessel-av

**Comment by rwaldron** [comment]
Please try the latest 0.10.0 and report back—thanks!
