### ISSUE TITLE
Camera width/height limit

### ISSUE THREAD

**Issue by Rowno** [tessel/tessel-av#9]
Is there a reason why the camera width/height can't be set higher than the default values?

**Comment by rwaldron** [comment]
I spent a lot of time implementing the frame streaming in this module and this limitation emerged as an optimization that allowed me to align "frame" with "data" event, by preventing the frame size from ever exceeding the high water mark (~64K). The Tessel 2 is very powerful, but must still be considered a resource constrained system. This restriction keeps you in a safe zone will also allowing your application to smoothly stream frames outbound (via web socket or whatever). An earlier iteration allowed for any size dimensions and would fill up a buffer as data was received and then emit the frame when it was it complete. The result was that the program would get bogged down trying to keep up with frame data and ultimately the process would crash or you'd get long pauses. 

I'm open to discussing new strategies.

**Comment by aaronshaf** [comment]
@rwaldron Are those constraints necessary for both camera-still and video mode?

**Comment by rwaldron** [comment]
Should be resolved with v0.10.0, now supports whatever the camera supports
